### ISSUE TITLE
Path sub-string is added to User on LDNetworkShare if path has more than 2 directories

### ISSUE THREAD

**Issue by altjones** [b1kjsh/LDMSPowershellTools#1]
If a network path is more than 2 levels deep the levels after the second gets added to the name field.

**Comment by ghost** [comment]
@altjones Can you provide the "net share {sharename}" output of an example share you're seeing this happen on?

**Comment by altjones** [comment]
Sorry I am confused on what you are asking...
Here is the output from the PS script....
(test should be part of the path and not the name)

Drive Letter is Z
Path is \\opwbl01\nettools\
User is Test User
__GENUS          : 2
__CLASS          : LDNetworkDrive
__SUPERCLASS     :
__DYNASTY        : LDNetworkDrive
__RELPATH        : LDNetworkDrive.Letter="Z",Path="\\\\opwbl01\\nettools\\",User="Test User"
__PROPERTY_COUNT : 3
__DERIVATION     : {}
__SERVER         : I31222
__NAMESPACE      : ROOT\cimv2
__PATH           : \\I31222\ROOT\cimv2:LDNetworkDrive.Letter="Z",Path="\\\\opwbl01\\nettools\\",User="Test User
                   "
Letter           : Z
Path             : \\opwbl01\nettools\
User             : Test User
PSComputerName   : I31222

**Comment by altjones** [comment]
I should of put this in the original issue, this is with the mapped drives and not local shares.

**Comment by ghost** [comment]
@altjones Fixed this, current script is available in the master branch. It won't be on the ivanti community document since I no longer work there. Hope it helps.

**Comment by altjones** [comment]
New issue.... Output of PS:

ErrorRecord                 : Method invocation failed because [Microsoft.PowerShell.Commands.Internal.Format.FormatStartData] does not contain a method named 'Substring'.
WasThrownFromThrowStatement : False
Message                     : Method invocation failed because [Microsoft.PowerShell.Commands.Internal.Format.FormatStartData] does not contain a method named 'Substring'.
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              :
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087

**Comment by ghost** [comment]
@altjones Fixed, see #2 and the associated commit. Please make a new issue on https://github.com/basilgarrad813/LDMSPowershellTools if you encounter a future issue.
